package com.hongsi.item.vo;

import lombok.Data;

@Data
public class ItemVO {
	
	private long cno;
	private String code;
	private String name;

}

/*

CREATE TABLE ITEM ( 
CNO NUMBER NOT NULL PRIMARY KEY, 
CODE VARCHAR2(20), 
NAME VARCHAR2(50), 
RDATE DATE DEFAULT SYSDATE);

CREATE SEQUENCE ITEM_PK
INCREMENT BY 1
START WITH 1
MAXVALUE 999;
 
INSERT INTO ITEM (CNO,CODE,NAME,RDATE) VALUES (ITEM_PK.NEXTVAL,'ORI','ORIGINAL', SYSDATE);
INSERT INTO ITEM (CNO,CODE,NAME,RDATE) VALUES (ITEM_PK.NEXTVAL,'ERL','EARLGREY', SYSDATE);
INSERT INTO ITEM (CNO,CODE,NAME,RDATE) VALUES (ITEM_PK.NEXTVAL,'STC','SALTCARAMEL', SYSDATE);
 
 */
