package com.hongsi.itemqtytype.vo;

import lombok.Data;

@Data
public class ItemQtyTypeVO {

	private long 	cno;
	private String 	code;
	private String 	name;
	private long 	amount;
	private String 	itemcode;

}

/*

CREATE TABLE ITEM_QTY_TYPE (
CNO NUMBER NOT NULL PRIMARY KEY,
ITEMCODE VARCHAR2(20), 
CODE VARCHAR2(20), 
NAME VARCHAR2(50), 
AMOUNT NUMBER DEFAULT 0,
RDATE DATE DEFAULT SYSDATE ); 

CREATE SEQUENCE ITEM_QTY_TYPE_PK
INCREMENT BY 1
START WITH 1
MAXVALUE 999;

Insert into ITEM_QTY_TYPE (CNO,ITEMCODE,CODE,NAME,AMOUNT,RDATE) values (ITEM_QTY_TYPE_PK.NEXTVAL,'ORI','ORI_100_001','ORI_100',100,SYSDATE);
Insert into ITEM_QTY_TYPE (CNO,ITEMCODE,CODE,NAME,AMOUNT,RDATE) values (ITEM_QTY_TYPE_PK.NEXTVAL,'ERL','ERL_100_001','ERL_100',100,SYSDATE);
Insert into ITEM_QTY_TYPE (CNO,ITEMCODE,CODE,NAME,AMOUNT,RDATE) values (ITEM_QTY_TYPE_PK.NEXTVAL,'STC','STC_100_001','STC_100',100,SYSDATE);


*/